package com.microsoft.hpc.dataservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-05-16T11:07:37.962+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hpc.microsoft.com/dataservice/", name = "IDataService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IDataService {

    @Action(input = "http://hpc.microsoft.com/dataservice/IDataService/DeleteDataClient", output = "http://hpc.microsoft.com/dataservice/IDataService/DeleteDataClientResponse", fault = {@FaultAction(className = IDataServiceDeleteDataClientDataFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/dataservice/DataFault")})
    @RequestWrapper(localName = "DeleteDataClient", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.DeleteDataClient")
    @WebMethod(operationName = "DeleteDataClient", action = "http://hpc.microsoft.com/dataservice/IDataService/DeleteDataClient")
    @ResponseWrapper(localName = "DeleteDataClientResponse", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.DeleteDataClientResponse")
    public void deleteDataClient(
        @WebParam(name = "dataClientId", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        java.lang.String dataClientId
    ) throws IDataServiceDeleteDataClientDataFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/dataservice/IDataService/AssociateDataClientWithSession", output = "http://hpc.microsoft.com/dataservice/IDataService/AssociateDataClientWithSessionResponse", fault = {@FaultAction(className = IDataServiceAssociateDataClientWithSessionDataFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/dataservice/DataFault")})
    @RequestWrapper(localName = "AssociateDataClientWithSession", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.AssociateDataClientWithSession")
    @WebMethod(operationName = "AssociateDataClientWithSession", action = "http://hpc.microsoft.com/dataservice/IDataService/AssociateDataClientWithSession")
    @ResponseWrapper(localName = "AssociateDataClientWithSessionResponse", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.AssociateDataClientWithSessionResponse")
    public void associateDataClientWithSession(
        @WebParam(name = "dataClientId", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        java.lang.String dataClientId,
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        java.lang.Integer sessionId
    ) throws IDataServiceAssociateDataClientWithSessionDataFaultFaultFaultMessage;

    @WebResult(name = "CreateDataClientResult", targetNamespace = "http://hpc.microsoft.com/dataservice/")
    @Action(input = "http://hpc.microsoft.com/dataservice/IDataService/CreateDataClient", output = "http://hpc.microsoft.com/dataservice/IDataService/CreateDataClientResponse", fault = {@FaultAction(className = IDataServiceCreateDataClientDataFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/dataservice/DataFault")})
    @RequestWrapper(localName = "CreateDataClient", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.CreateDataClient")
    @WebMethod(operationName = "CreateDataClient", action = "http://hpc.microsoft.com/dataservice/IDataService/CreateDataClient")
    @ResponseWrapper(localName = "CreateDataClientResponse", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.CreateDataClientResponse")
    public java.lang.String createDataClient(
        @WebParam(name = "dataClientId", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        java.lang.String dataClientId,
        @WebParam(name = "allowedUsers", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring allowedUsers
    ) throws IDataServiceCreateDataClientDataFaultFaultFaultMessage;

    @WebResult(name = "OpenDataClientResult", targetNamespace = "http://hpc.microsoft.com/dataservice/")
    @Action(input = "http://hpc.microsoft.com/dataservice/IDataService/OpenDataClient", output = "http://hpc.microsoft.com/dataservice/IDataService/OpenDataClientResponse", fault = {@FaultAction(className = IDataServiceOpenDataClientDataFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/dataservice/DataFault")})
    @RequestWrapper(localName = "OpenDataClient", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.OpenDataClient")
    @WebMethod(operationName = "OpenDataClient", action = "http://hpc.microsoft.com/dataservice/IDataService/OpenDataClient")
    @ResponseWrapper(localName = "OpenDataClientResponse", targetNamespace = "http://hpc.microsoft.com/dataservice/", className = "com.microsoft.hpc.dataservice.OpenDataClientResponse")
    public java.lang.String openDataClient(
        @WebParam(name = "dataClientId", targetNamespace = "http://hpc.microsoft.com/dataservice/")
        java.lang.String dataClientId
    ) throws IDataServiceOpenDataClientDataFaultFaultFaultMessage;
}
