
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-18T10:11:49.065+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "RetryOperationError", targetNamespace = "http://hpc.microsoft.com/session/")
public class ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20120918101149L;
    
    private com.microsoft.hpc.session.RetryOperationError retryOperationError;

    public ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.session.RetryOperationError retryOperationError) {
        super(message);
        this.retryOperationError = retryOperationError;
    }

    public ITestServiceEchoWithFailRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.session.RetryOperationError retryOperationError, Throwable cause) {
        super(message, cause);
        this.retryOperationError = retryOperationError;
    }

    public com.microsoft.hpc.session.RetryOperationError getFaultInfo() {
        return this.retryOperationError;
    }
}
