
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-04-14T16:08:10.724+08:00
 * Generated source version: 2.3.3
 * 
 */
 
public class ITestService_DefaultBindingITestService_Server{

    protected ITestService_DefaultBindingITestService_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ITestServiceImpl();
        String address = "http://localhost:9200/Broker";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ITestService_DefaultBindingITestService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(50 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
