
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-18T10:11:49.217+08:00
 * Generated source version: 2.4.0
 * 
 */
 
public class ITestService_DefaultBindingITestService_Server{

    protected ITestService_DefaultBindingITestService_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ITestServiceImpl();
        String address = "https://localhost/Broker";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ITestService_DefaultBindingITestService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
