
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-04-14T16:08:10.603+08:00
 * Generated source version: 2.3.3
 * 
 */

@WebFault(name = "RetryOperationError", targetNamespace = "http://hpc.microsoft.com/session/")
public class ITestServiceEchoRetryOperationErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110414160810L;
    
    private com.microsoft.hpc.aitestsvclib.session.RetryOperationError retryOperationError;

    public ITestServiceEchoRetryOperationErrorFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoRetryOperationErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoRetryOperationErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.aitestsvclib.session.RetryOperationError retryOperationError) {
        super(message);
        this.retryOperationError = retryOperationError;
    }

    public ITestServiceEchoRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.aitestsvclib.session.RetryOperationError retryOperationError, Throwable cause) {
        super(message, cause);
        this.retryOperationError = retryOperationError;
    }

    public com.microsoft.hpc.aitestsvclib.session.RetryOperationError getFaultInfo() {
        return this.retryOperationError;
    }
}
