
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-18T10:11:49.047+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "DivideByZeroException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20120918101149L;
    
    private org.datacontract.schemas._2004._07.system.DivideByZeroException divideByZeroException;

    public ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.DivideByZeroException divideByZeroException) {
        super(message);
        this.divideByZeroException = divideByZeroException;
    }

    public ITestServiceEchoFaultWithNameDivideByZeroExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.DivideByZeroException divideByZeroException, Throwable cause) {
        super(message, cause);
        this.divideByZeroException = divideByZeroException;
    }

    public org.datacontract.schemas._2004._07.system.DivideByZeroException getFaultInfo() {
        return this.divideByZeroException;
    }
}
