
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-04-14T16:08:10.504+08:00
 * Generated source version: 2.3.3
 * 
 */

@WebFault(name = "AuthenticationFailure", targetNamespace = "http://hpc.microsoft.com/session/")
public class ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110414160810L;
    
    private com.microsoft.hpc.aitestsvclib.session.AuthenticationFailure authenticationFailure;

    public ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage(String message, com.microsoft.hpc.aitestsvclib.session.AuthenticationFailure authenticationFailure) {
        super(message);
        this.authenticationFailure = authenticationFailure;
    }

    public ITestServiceEchoWithDelayAuthenticationFailureFaultFaultMessage(String message, com.microsoft.hpc.aitestsvclib.session.AuthenticationFailure authenticationFailure, Throwable cause) {
        super(message, cause);
        this.authenticationFailure = authenticationFailure;
    }

    public com.microsoft.hpc.aitestsvclib.session.AuthenticationFailure getFaultInfo() {
        return this.authenticationFailure;
    }
}
