
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-18T10:11:49.084+08:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "ArgumentNullException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20120918101149L;
    
    private org.datacontract.schemas._2004._07.system.ArgumentNullException argumentNullException;

    public ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentNullException argumentNullException) {
        super(message);
        this.argumentNullException = argumentNullException;
    }

    public ITestServiceEchoFaultArgumentNullExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.ArgumentNullException argumentNullException, Throwable cause) {
        super(message, cause);
        this.argumentNullException = argumentNullException;
    }

    public org.datacontract.schemas._2004._07.system.ArgumentNullException getFaultInfo() {
        return this.argumentNullException;
    }
}
