
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-04-14T16:08:10.259+08:00
 * Generated source version: 2.3.3
 * 
 */

@WebFault(name = "CommonDataError", targetNamespace = "http://schemas.datacontract.org/2004/07/AITestLib.Helper")
public class ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110414160810L;
    
    private org.datacontract.schemas._2004._07.aitestlib.CommonDataError commonDataError;

    public ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage() {
        super();
    }
    
    public ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.aitestlib.CommonDataError commonDataError) {
        super(message);
        this.commonDataError = commonDataError;
    }

    public ITestServiceGetCommonDataCommonDataErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.aitestlib.CommonDataError commonDataError, Throwable cause) {
        super(message, cause);
        this.commonDataError = commonDataError;
    }

    public org.datacontract.schemas._2004._07.aitestlib.CommonDataError getFaultInfo() {
        return this.commonDataError;
    }
}
