
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-04-14T16:08:10.441+08:00
 * Generated source version: 2.3.3
 * 
 */

@WebFault(name = "OutOfMemoryException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110414160810L;
    
    private org.datacontract.schemas._2004._07.system.OutOfMemoryException outOfMemoryException;

    public ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage() {
        super();
    }
    
    public ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.OutOfMemoryException outOfMemoryException) {
        super(message);
        this.outOfMemoryException = outOfMemoryException;
    }

    public ITestServiceEchoFaultOutOfMemoryExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.OutOfMemoryException outOfMemoryException, Throwable cause) {
        super(message, cause);
        this.outOfMemoryException = outOfMemoryException;
    }

    public org.datacontract.schemas._2004._07.system.OutOfMemoryException getFaultInfo() {
        return this.outOfMemoryException;
    }
}
