
/*
 * 
 */

package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-17T18:19:06.589+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "JavaAITestSvcLib", 
                  wsdlLocation = "file:tempuri.org.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class JavaAITestSvcLib extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "JavaAITestSvcLib");
    public final static QName DefaultBindingITestService = new QName("http://tempuri.org/", "DefaultBinding_ITestService");
    static {
        URL url = null;
        try {
            url = new URL("file:tempuri.org.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JavaAITestSvcLib.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:tempuri.org.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JavaAITestSvcLib(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JavaAITestSvcLib(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JavaAITestSvcLib() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JavaAITestSvcLib(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JavaAITestSvcLib(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JavaAITestSvcLib(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITestService
     */
    @WebEndpoint(name = "DefaultBinding_ITestService")
    public ITestService getDefaultBindingITestService() {
        return super.getPort(DefaultBindingITestService, ITestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITestService
     */
    @WebEndpoint(name = "DefaultBinding_ITestService")
    public ITestService getDefaultBindingITestService(WebServiceFeature... features) {
        return super.getPort(DefaultBindingITestService, ITestService.class, features);
    }

}
