
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-03-11T14:28:00.260+08:00
 * Generated source version: 2.3.3
 * 
 * This class is unnecessary for JavaSvcHost to load the service.
 * It's included for debug purpose, so that to provide a naive host. 
 */
 
public class IEchoSvc_DefaultBindingIEchoSvc_Server{

    protected IEchoSvc_DefaultBindingIEchoSvc_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IEchoSvcImpl();
        String address = "http://localhost:9000/EchoSvc";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new IEchoSvc_DefaultBindingIEchoSvc_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
