package com.microsoft.hpc.brokercontroller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Apr 08 15:42:01 CST 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://hpc.microsoft.com/brokercontroller/", name = "IBrokerController")
@XmlSeeAlso({com.microsoft.hpc.ObjectFactory.class, com.microsoft.hpc.session.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IBrokerController {

    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/EndRequests", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/EndRequestsResponse", fault = {@FaultAction(className = IBrokerControllerEndRequestsSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "EndRequests", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.EndRequests")
    @WebMethod(operationName = "EndRequests", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/EndRequests")
    @ResponseWrapper(localName = "EndRequestsResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.EndRequestsResponse")
    public void endRequests(
        @WebParam(name = "count", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer count,
        @WebParam(name = "clientid", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientid,
        @WebParam(name = "timeoutThrottlingMs", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer timeoutThrottlingMs,
        @WebParam(name = "timeoutEOMMs", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer timeoutEOMMs
    ) throws IBrokerControllerEndRequestsSessionFaultFaultFaultMessage;

    @WebResult(name = "GetRequestsCountResult", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetRequestsCount", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetRequestsCountResponse", fault = {@FaultAction(className = IBrokerControllerGetRequestsCountSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetRequestsCount", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.GetRequestsCount")
    @WebMethod(operationName = "GetRequestsCount", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetRequestsCount")
    @ResponseWrapper(localName = "GetRequestsCountResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.GetRequestsCountResponse")
    public java.lang.Integer getRequestsCount(
        @WebParam(name = "clientId", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientId
    ) throws IBrokerControllerGetRequestsCountSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/Flush", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/FlushResponse", fault = {@FaultAction(className = IBrokerControllerFlushSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Flush", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.Flush")
    @WebMethod(operationName = "Flush", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/Flush")
    @ResponseWrapper(localName = "FlushResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.FlushResponse")
    public void flush(
        @WebParam(name = "count", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer count,
        @WebParam(name = "clientid", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientid,
        @WebParam(name = "timeoutThrottlingMs", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer timeoutThrottlingMs,
        @WebParam(name = "timeoutFlushMs", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.Integer timeoutFlushMs
    ) throws IBrokerControllerFlushSessionFaultFaultFaultMessage;

    @WebResult(name = "GetBrokerClientStatusResult", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetBrokerClientStatus", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetBrokerClientStatusResponse", fault = {@FaultAction(className = IBrokerControllerGetBrokerClientStatusSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetBrokerClientStatus", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.GetBrokerClientStatus")
    @WebMethod(operationName = "GetBrokerClientStatus", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/GetBrokerClientStatus")
    @ResponseWrapper(localName = "GetBrokerClientStatusResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.GetBrokerClientStatusResponse")
    public com.microsoft.hpc.BrokerClientStatus getBrokerClientStatus(
        @WebParam(name = "clientId", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientId
    ) throws IBrokerControllerGetBrokerClientStatusSessionFaultFaultFaultMessage;

    @WebResult(name = "PullResponsesResult", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/PullResponses", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/PullResponsesResponse", fault = {@FaultAction(className = IBrokerControllerPullResponsesSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "PullResponses", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.PullResponses")
    @WebMethod(operationName = "PullResponses", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/PullResponses")
    @ResponseWrapper(localName = "PullResponsesResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.PullResponsesResponse")
    public com.microsoft.hpc.brokercontroller.BrokerResponseMessages pullResponses(
        @WebParam(name = "action", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String action,
        @WebParam(name = "position", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        com.microsoft.hpc.brokercontroller.GetResponsePosition position,
        @WebParam(name = "count", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        int count,
        @WebParam(name = "clientId", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientId
    ) throws IBrokerControllerPullResponsesSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/brokercontroller/IBrokerController/Purge", output = "http://hpc.microsoft.com/brokercontroller/IBrokerController/PurgeResponse", fault = {@FaultAction(className = IBrokerControllerPurgeSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Purge", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.Purge")
    @WebMethod(operationName = "Purge", action = "http://hpc.microsoft.com/brokercontroller/IBrokerController/Purge")
    @ResponseWrapper(localName = "PurgeResponse", targetNamespace = "http://hpc.microsoft.com/brokercontroller/", className = "com.microsoft.hpc.brokercontroller.PurgeResponse")
    public void purge(
        @WebParam(name = "clientid", targetNamespace = "http://hpc.microsoft.com/brokercontroller/")
        java.lang.String clientid
    ) throws IBrokerControllerPurgeSessionFaultFaultFaultMessage;
}
