
package com.microsoft.hpc.brokercontroller;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Apr 08 15:42:01 CST 2011
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "SessionFault", targetNamespace = "http://hpc.microsoft.com/session/")
public class IBrokerControllerFlushSessionFaultFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110408154201L;
    
    private com.microsoft.hpc.session.SessionFault sessionFault;

    public IBrokerControllerFlushSessionFaultFaultFaultMessage() {
        super();
    }
    
    public IBrokerControllerFlushSessionFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IBrokerControllerFlushSessionFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IBrokerControllerFlushSessionFaultFaultFaultMessage(String message, com.microsoft.hpc.session.SessionFault sessionFault) {
        super(message);
        this.sessionFault = sessionFault;
    }

    public IBrokerControllerFlushSessionFaultFaultFaultMessage(String message, com.microsoft.hpc.session.SessionFault sessionFault, Throwable cause) {
        super(message, cause);
        this.sessionFault = sessionFault;
    }

    public com.microsoft.hpc.session.SessionFault getFaultInfo() {
        return this.sessionFault;
    }
}
