
/*
 * 
 */

package com.microsoft.hpc.genericservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Mar 17 19:45:34 CST 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "GenericService", 
                  wsdlLocation = "file:hpc.microsoft.com.GenericService.wsdl",
                  targetNamespace = "http://hpc.microsoft.com/GenericService") 
public class GenericService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://hpc.microsoft.com/GenericService", "GenericService");
    public final static QName DefaultBindingIGenericService = new QName("http://hpc.microsoft.com/GenericService", "DefaultBinding_IGenericService");
    static {
        URL url = null;
        try {
            url = new URL("file:hpc.microsoft.com.GenericService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:hpc.microsoft.com.GenericService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GenericService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenericService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GenericService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public GenericService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GenericService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGenericService
     */
    @WebEndpoint(name = "DefaultBinding_IGenericService")
    public IGenericService getDefaultBindingIGenericService() {
        return super.getPort(DefaultBindingIGenericService, IGenericService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGenericService
     */
    @WebEndpoint(name = "DefaultBinding_IGenericService")
    public IGenericService getDefaultBindingIGenericService(WebServiceFeature... features) {
        return super.getPort(DefaultBindingIGenericService, IGenericService.class, features);
    }

}
