
package com.microsoft.hpc.genericservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Mar 17 19:45:34 CST 2011
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "RetryOperationError", targetNamespace = "http://hpc.microsoft.com/session/")
public class IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110317194534L;
    
    private com.microsoft.hpc.session.RetryOperationError retryOperationError;

    public IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage() {
        super();
    }
    
    public IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.session.RetryOperationError retryOperationError) {
        super(message);
        this.retryOperationError = retryOperationError;
    }

    public IGenericServiceGenericOperationRetryOperationErrorFaultFaultMessage(String message, com.microsoft.hpc.session.RetryOperationError retryOperationError, Throwable cause) {
        super(message, cause);
        this.retryOperationError = retryOperationError;
    }

    public com.microsoft.hpc.session.RetryOperationError getFaultInfo() {
        return this.retryOperationError;
    }
}
