
/*
 * 
 */

package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Dec 28 11:00:17 GMT+08:00 2010
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "CcpEchoSvc", 
                  wsdlLocation = "file:tempuri.org.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class CcpEchoSvc extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "CcpEchoSvc");
    public final static QName DefaultBindingIEchoSvc = new QName("http://tempuri.org/", "DefaultBinding_IEchoSvc");
    static {
        URL url = null;
        try {
            url = new URL("file:tempuri.org.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:tempuri.org.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CcpEchoSvc(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CcpEchoSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcpEchoSvc() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IEchoSvc
     */
    @WebEndpoint(name = "DefaultBinding_IEchoSvc")
    public IEchoSvc getDefaultBindingIEchoSvc() {
        return super.getPort(DefaultBindingIEchoSvc, IEchoSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEchoSvc
     */
    @WebEndpoint(name = "DefaultBinding_IEchoSvc")
    public IEchoSvc getDefaultBindingIEchoSvc(WebServiceFeature... features) {
        return super.getPort(DefaultBindingIEchoSvc, IEchoSvc.class, features);
    }

}
