package com.microsoft.hpc.brokerlauncher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Dec 13 16:05:47 GMT+08:00 2010
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", name = "IBrokerLauncher")
@XmlSeeAlso({org.datacontract.schemas._2004._07.microsoft_hpc_scheduler.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.hpc.ObjectFactory.class, ObjectFactory.class, com.microsoft.hpc.session.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IBrokerLauncher {

    @WebResult(name = "AttachResult", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Attach", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/AttachResponse", fault = {@FaultAction(className = IBrokerLauncherAttachSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Attach", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.Attach")
    @WebMethod(operationName = "Attach", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Attach")
    @ResponseWrapper(localName = "AttachResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.AttachResponse")
    public com.microsoft.hpc.brokerlauncher.BrokerInitializationResult attach(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        java.lang.Integer sessionId
    ) throws IBrokerLauncherAttachSessionFaultFaultFaultMessage;

    @WebResult(name = "PingBrokerResult", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/PingBroker", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/PingBrokerResponse", fault = {@FaultAction(className = IBrokerLauncherPingBrokerSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "PingBroker", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.PingBroker")
    @WebMethod(operationName = "PingBroker", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/PingBroker")
    @ResponseWrapper(localName = "PingBrokerResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.PingBrokerResponse")
    public java.lang.Boolean pingBroker(
        @WebParam(name = "sessionID", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        java.lang.Integer sessionID
    ) throws IBrokerLauncherPingBrokerSessionFaultFaultFaultMessage;

    @WebResult(name = "CreateDurableResult", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/CreateDurable", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/CreateDurableResponse", fault = {@FaultAction(className = IBrokerLauncherCreateDurableSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "CreateDurable", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.CreateDurable")
    @WebMethod(operationName = "CreateDurable", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/CreateDurable")
    @ResponseWrapper(localName = "CreateDurableResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.CreateDurableResponse")
    public com.microsoft.hpc.brokerlauncher.BrokerInitializationResult createDurable(
        @WebParam(name = "info", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        com.microsoft.hpc.SessionStartInfoContract info,
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        java.lang.Integer sessionId
    ) throws IBrokerLauncherCreateDurableSessionFaultFaultFaultMessage;

    @WebResult(name = "CreateResult", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Create", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/CreateResponse", fault = {@FaultAction(className = IBrokerLauncherCreateSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Create", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.Create")
    @WebMethod(operationName = "Create", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.CreateResponse")
    public com.microsoft.hpc.brokerlauncher.BrokerInitializationResult create(
        @WebParam(name = "info", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        com.microsoft.hpc.SessionStartInfoContract info,
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        java.lang.Integer sessionId
    ) throws IBrokerLauncherCreateSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Close", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/CloseResponse", fault = {@FaultAction(className = IBrokerLauncherCloseSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Close", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.Close")
    @WebMethod(operationName = "Close", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/Close")
    @ResponseWrapper(localName = "CloseResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.CloseResponse")
    public void close(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
        java.lang.Integer sessionId
    ) throws IBrokerLauncherCloseSessionFaultFaultFaultMessage;

    @WebResult(name = "GetActiveBrokerIdListResult", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/")
    @Action(input = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/GetActiveBrokerIdList", output = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/GetActiveBrokerIdListResponse", fault = {@FaultAction(className = IBrokerLauncherGetActiveBrokerIdListSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetActiveBrokerIdList", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.GetActiveBrokerIdList")
    @WebMethod(operationName = "GetActiveBrokerIdList", action = "http://hpc.microsoft.com/brokerlauncher/IBrokerLauncher/GetActiveBrokerIdList")
    @ResponseWrapper(localName = "GetActiveBrokerIdListResponse", targetNamespace = "http://hpc.microsoft.com/brokerlauncher/", className = "com.microsoft.hpc.brokerlauncher.GetActiveBrokerIdListResponse")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint getActiveBrokerIdList() throws IBrokerLauncherGetActiveBrokerIdListSessionFaultFaultFaultMessage;
}
