//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StatisticInfo", Namespace = "http://schemas.datacontract.org/2004/07/EchoSvcLib")]
    public partial class StatisticInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime endTimeField;

        private System.DateTime startTimeField;

        private int taskIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IEchoSvc")]
    public interface IEchoSvc
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        EchoResponse Echo(EchoRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        System.IAsyncResult BeginEcho(EchoRequest request, System.AsyncCallback callback, object asyncState);

        EchoResponse EndEcho(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        GenerateLoadResponse GenerateLoad(GenerateLoadRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        System.IAsyncResult BeginGenerateLoad(GenerateLoadRequest request, System.AsyncCallback callback, object asyncState);

        GenerateLoadResponse EndGenerateLoad(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/EchoData", ReplyAction = "http://tempuri.org/IEchoSvc/EchoDataResponse")]
        EchoDataResponse EchoData(EchoDataRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/EchoData", ReplyAction = "http://tempuri.org/IEchoSvc/EchoDataResponse")]
        System.IAsyncResult BeginEchoData(EchoDataRequest request, System.AsyncCallback callback, object asyncState);

        EchoDataResponse EndEchoData(System.IAsyncResult result);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Echo", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string input;

        public EchoRequest()
        {
        }

        public EchoRequest(string input)
        {
            this.input = input;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string EchoResult;

        public EchoResponse()
        {
        }

        public EchoResponse(string EchoResult)
        {
            this.EchoResult = EchoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerateLoad", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GenerateLoadRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public double runMilliSeconds;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public byte[] dummyData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public string fileData;

        public GenerateLoadRequest()
        {
        }

        public GenerateLoadRequest(double runMilliSeconds, byte[] dummyData, string fileData)
        {
            this.runMilliSeconds = runMilliSeconds;
            this.dummyData = dummyData;
            this.fileData = fileData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GenerateLoadResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GenerateLoadResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public EchoService.StatisticInfo GenerateLoadResult;

        public GenerateLoadResponse()
        {
        }

        public GenerateLoadResponse(EchoService.StatisticInfo GenerateLoadResult)
        {
            this.GenerateLoadResult = GenerateLoadResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoData", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string dataClientId;

        public EchoDataRequest()
        {
        }

        public EchoDataRequest(string dataClientId)
        {
            this.dataClientId = dataClientId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoDataResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class EchoDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int EchoDataResult;

        public EchoDataResponse()
        {
        }

        public EchoDataResponse(int EchoDataResult)
        {
            this.EchoDataResult = EchoDataResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEchoSvcChannel : IEchoSvc, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EchoSvcClient : System.ServiceModel.ClientBase<IEchoSvc>, IEchoSvc
    {

        public EchoSvcClient()
        {
        }

        public EchoSvcClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public EchoResponse Echo(EchoRequest request)
        {
            return base.Channel.Echo(request);
        }

        public System.IAsyncResult BeginEcho(EchoRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginEcho(request, callback, asyncState);
        }

        public EchoResponse EndEcho(System.IAsyncResult result)
        {
            return base.Channel.EndEcho(result);
        }

        public GenerateLoadResponse GenerateLoad(GenerateLoadRequest request)
        {
            return base.Channel.GenerateLoad(request);
        }

        public System.IAsyncResult BeginGenerateLoad(GenerateLoadRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGenerateLoad(request, callback, asyncState);
        }

        public GenerateLoadResponse EndGenerateLoad(System.IAsyncResult result)
        {
            return base.Channel.EndGenerateLoad(result);
        }

        public EchoDataResponse EchoData(EchoDataRequest request)
        {
            return base.Channel.EchoData(request);
        }

        public System.IAsyncResult BeginEchoData(EchoDataRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginEchoData(request, callback, asyncState);
        }

        public EchoDataResponse EndEchoData(System.IAsyncResult result)
        {
            return base.Channel.EndEchoData(result);
        }
    }

}

