
package com.microsoft.hpc.genericservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Mar 17 19:45:34 CST 2011
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "AuthenticationFailure", targetNamespace = "http://hpc.microsoft.com/session/")
public class IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20110317194534L;
    
    private com.microsoft.hpc.session.AuthenticationFailure authenticationFailure;

    public IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage() {
        super();
    }
    
    public IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage(String message) {
        super(message);
    }
    
    public IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage(String message, com.microsoft.hpc.session.AuthenticationFailure authenticationFailure) {
        super(message);
        this.authenticationFailure = authenticationFailure;
    }

    public IGenericServiceGenericOperationAuthenticationFailureFaultFaultMessage(String message, com.microsoft.hpc.session.AuthenticationFailure authenticationFailure, Throwable cause) {
        super(message, cause);
        this.authenticationFailure = authenticationFailure;
    }

    public com.microsoft.hpc.session.AuthenticationFailure getFaultInfo() {
        return this.authenticationFailure;
    }
}
