package com.microsoft.hpc.sessionlauncher;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Mar 21 17:06:38 CST 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", name = "ISessionLauncher")
@XmlSeeAlso({org.datacontract.schemas._2004._07.microsoft_hpc_scheduler.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.hpc.ObjectFactory.class, com.microsoft.hpc.session.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class})
public interface ISessionLauncher {

    @WebResult(name = "GetSOAConfigurationResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetSOAConfiguration", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetSOAConfigurationResponse", fault = {@FaultAction(className = ISessionLauncherGetSOAConfigurationSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetSOAConfiguration", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetSOAConfiguration")
    @WebMethod(operationName = "GetSOAConfiguration", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetSOAConfiguration")
    @ResponseWrapper(localName = "GetSOAConfigurationResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetSOAConfigurationResponse")
    public java.lang.String getSOAConfiguration(
        @WebParam(name = "key", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String key
    ) throws ISessionLauncherGetSOAConfigurationSessionFaultFaultFaultMessage;

    @WebResult(name = "GetServerVersionResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServerVersion", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServerVersionResponse", fault = {@FaultAction(className = ISessionLauncherGetServerVersionSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetServerVersion", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetServerVersion")
    @WebMethod(operationName = "GetServerVersion", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServerVersion")
    @ResponseWrapper(localName = "GetServerVersionResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetServerVersionResponse")
    public org.datacontract.schemas._2004._07.system.Version getServerVersion() throws ISessionLauncherGetServerVersionSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/AllocateDurable", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/AllocateDurableResponse", fault = {@FaultAction(className = ISessionLauncherAllocateDurableSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "AllocateDurable", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.AllocateDurable")
    @WebMethod(operationName = "AllocateDurable", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/AllocateDurable")
    @ResponseWrapper(localName = "AllocateDurableResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.AllocateDurableResponse")
    public void allocateDurable(
        @WebParam(name = "info", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        com.microsoft.hpc.SessionStartInfoContract info,
        @WebParam(name = "endpointPrefix", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String endpointPrefix,
        @WebParam(mode = WebParam.Mode.OUT, name = "AllocateDurableResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring> allocateDurableResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "sessionid", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<java.lang.Integer> sessionid,
        @WebParam(mode = WebParam.Mode.OUT, name = "serviceVersion", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<java.lang.String> serviceVersion
    ) throws ISessionLauncherAllocateDurableSessionFaultFaultFaultMessage;

    @WebResult(name = "GetInfoResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetInfo", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetInfoResponse", fault = {@FaultAction(className = ISessionLauncherGetInfoSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetInfo")
    @WebMethod(operationName = "GetInfo", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetInfoResponse")
    public com.microsoft.hpc.sessionlauncher.SessionInfo getInfo(
        @WebParam(name = "headnode", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String headnode,
        @WebParam(name = "endpointPrefix", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String endpointPrefix,
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.Integer sessionId
    ) throws ISessionLauncherGetInfoSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/Allocate", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/AllocateResponse", fault = {@FaultAction(className = ISessionLauncherAllocateSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Allocate", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.Allocate")
    @WebMethod(operationName = "Allocate", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/Allocate")
    @ResponseWrapper(localName = "AllocateResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.AllocateResponse")
    public void allocate(
        @WebParam(name = "info", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        com.microsoft.hpc.SessionStartInfoContract info,
        @WebParam(name = "endpointPrefix", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String endpointPrefix,
        @WebParam(mode = WebParam.Mode.OUT, name = "AllocateResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring> allocateResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "sessionid", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<java.lang.Integer> sessionid,
        @WebParam(mode = WebParam.Mode.OUT, name = "serviceVersion", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        javax.xml.ws.Holder<java.lang.String> serviceVersion
    ) throws ISessionLauncherAllocateSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/Terminate", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/TerminateResponse", fault = {@FaultAction(className = ISessionLauncherTerminateSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "Terminate", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.Terminate")
    @WebMethod(operationName = "Terminate", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/Terminate")
    @ResponseWrapper(localName = "TerminateResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.TerminateResponse")
    public void terminate(
        @WebParam(name = "headnode", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String headnode,
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.Integer sessionId
    ) throws ISessionLauncherTerminateSessionFaultFaultFaultMessage;

    @WebResult(name = "GetServiceVersionsResult", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
    @Action(input = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServiceVersions", output = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServiceVersionsResponse", fault = {@FaultAction(className = ISessionLauncherGetServiceVersionsSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "GetServiceVersions", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetServiceVersions")
    @WebMethod(operationName = "GetServiceVersions", action = "http://hpc.microsoft.com/sessionlauncher/ISessionLauncher/GetServiceVersions")
    @ResponseWrapper(localName = "GetServiceVersionsResponse", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/", className = "com.microsoft.hpc.sessionlauncher.GetServiceVersionsResponse")
    public org.datacontract.schemas._2004._07.system.ArrayOfVersion getServiceVersions(
        @WebParam(name = "serviceName", targetNamespace = "http://hpc.microsoft.com/sessionlauncher/")
        java.lang.String serviceName
    ) throws ISessionLauncherGetServiceVersionsSessionFaultFaultFaultMessage;
}
