/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_hpc_scheduler_session_servicecontext_etw_UserEvent */
#pragma   comment(lib,   "rpcrt4.lib")
#ifndef _Included_com_microsoft_hpc_scheduler_session_servicecontext_etw_UserEvent
#define _Included_com_microsoft_hpc_scheduler_session_servicecontext_etw_UserEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_hpc_scheduler_session_servicecontext_etw_UserEvent
 * Method:    CWriteUserEvent
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_hpc_scheduler_session_servicecontext_etw_UserEvent_CWriteUserEvent
  (JNIEnv *, jclass, jint, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
