//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
//+
// Provider Microsoft-HPC-Runtime Event Count 60
//+
EXTERN_C __declspec(selectany) const GUID RuntimeTrace = {0x8979efb0, 0x97da, 0x4729, {0x82, 0x96, 0xf1, 0x18, 0xf3, 0x56, 0x2a, 0x53}};

//
// Channel
//
#define RuntimeTrace_CHANNEL_AdminChannel 0x10
#define HPC_CHANNEL_Runtime_OP 0x11
#define DebugChannel 0x12
#define AnalyticChannel 0x13

//
// Tasks
//
#define DebugTrace 0x1
#define SessionLifecycle 0x2
#define Client 0x3
#define Dispatcher 0x4
#define FrontEnd 0x5
#define ServiceHost 0x6
#define RequestProcessing 0x7
#define BrokerWorker 0x8
#define UserTrace 0x9
#define HpcSessionTrace 0xa
//
// Keyword
//
#define TextTracing 0x1

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR TextVerbose = {0xa, 0x0, 0x13, 0x5, 0x0, 0x1, 0x1000000000000001};
#define TextVerbose_value 0xa
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR TextInfo = {0xb, 0x0, 0x13, 0x4, 0x0, 0x1, 0x1000000000000001};
#define TextInfo_value 0xb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR TextWarning = {0xc, 0x0, 0x13, 0x3, 0x0, 0x1, 0x1000000000000001};
#define TextWarning_value 0xc
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR TextError = {0xd, 0x0, 0x13, 0x2, 0x0, 0x1, 0x1000000000000001};
#define TextError_value 0xd
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR TextCritial = {0xe, 0x0, 0x13, 0x1, 0x0, 0x1, 0x1000000000000001};
#define TextCritial_value 0xe
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EventTextCritial = {0x271e, 0x0, 0x10, 0x1, 0x0, 0xa, 0x8000000000000001};
#define EventTextCritial_value 0x271e
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EventTextVerbose = {0x271a, 0x0, 0x12, 0x5, 0x0, 0xa, 0x2000000000000001};
#define EventTextVerbose_value 0x271a
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EventTextInfo = {0x271b, 0x0, 0x12, 0x4, 0x0, 0xa, 0x2000000000000001};
#define EventTextInfo_value 0x271b
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EventTextWarning = {0x271c, 0x0, 0x12, 0x3, 0x0, 0xa, 0x2000000000000001};
#define EventTextWarning_value 0x271c
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EventTextError = {0x271d, 0x0, 0x11, 0x2, 0x0, 0xa, 0x4000000000000001};
#define EventTextError_value 0x271d
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostRequestReceived = {0x3e8, 0x0, 0x13, 0x5, 0xf0, 0x6, 0x1000000000000000};
#define HostRequestReceived_value 0x3e8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostResponseSent = {0x3e9, 0x0, 0x13, 0x5, 0x6, 0x6, 0x1000000000000000};
#define HostResponseSent_value 0x3e9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostStart = {0x3ea, 0x0, 0x13, 0x4, 0x1, 0x6, 0x1000000000000000};
#define HostStart_value 0x3ea
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostStop = {0x3eb, 0x0, 0x13, 0x4, 0x2, 0x6, 0x1000000000000000};
#define HostStop_value 0x3eb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostServiceConfigCheck = {0x3ec, 0x0, 0x10, 0x3, 0x0, 0xa, 0x8000000000000000};
#define HostServiceConfigCheck_value 0x3ec
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostAssemblyLoaded = {0x3ed, 0x0, 0x13, 0x4, 0x0, 0x6, 0x1000000000000000};
#define HostAssemblyLoaded_value 0x3ed
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR HostCanceled = {0x3ee, 0x0, 0x13, 0x4, 0x0, 0x6, 0x1000000000000000};
#define HostCanceled_value 0x3ee
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestReceived = {0xbb8, 0x0, 0x13, 0x5, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestReceived_value 0xbb8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndResponseSent = {0xbb9, 0x0, 0x13, 0x5, 0x6, 0x7, 0x1000000000000000};
#define FrontEndResponseSent_value 0xbb9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendRequestSent = {0xbba, 0x0, 0x13, 0x5, 0x9, 0x7, 0x1000000000000000};
#define BackendRequestSent_value 0xbba
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendResponseReceived = {0xbbb, 0x0, 0x13, 0x5, 0xf0, 0x7, 0x1000000000000000};
#define BackendResponseReceived_value 0xbbb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendRequestSentFailed = {0xbbc, 0x0, 0x13, 0x3, 0x9, 0x7, 0x1000000000000000};
#define BackendRequestSentFailed_value 0xbbc
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendResponseReceivedFailed = {0xbbd, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define BackendResponseReceivedFailed_value 0xbbd
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndResponseSentFailed = {0xbbe, 0x0, 0x13, 0x3, 0x9, 0x7, 0x1000000000000000};
#define FrontEndResponseSentFailed_value 0xbbe
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestRejectedClientIdNotMatch = {0xbbf, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestRejectedClientIdNotMatch_value 0xbbf
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestRejectedClientIdInvalid = {0xbc0, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestRejectedClientIdInvalid_value 0xbc0
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestRejectedClientStateInvalid = {0xbc1, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestRejectedClientStateInvalid_value 0xbc1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendResponseReceivedRetryOperationError = {0xbc2, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define BackendResponseReceivedRetryOperationError_value 0xbc2
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendResponseReceivedRetryLimitExceed = {0xbc3, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define BackendResponseReceivedRetryLimitExceed_value 0xbc3
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendRequestPutBack = {0xbc4, 0x0, 0x13, 0x5, 0x9, 0x7, 0x1000000000000000};
#define BackendRequestPutBack_value 0xbc4
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendGeneratedFaultReply = {0xbc5, 0x0, 0x13, 0x5, 0xf0, 0x7, 0x1000000000000000};
#define BackendGeneratedFaultReply_value 0xbc5
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestRejectedAuthenticationError = {0xbc6, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestRejectedAuthenticationError_value 0xbc6
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FrontEndRequestRejectedGeneralError = {0xbc7, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define FrontEndRequestRejectedGeneralError_value 0xbc7
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendHandleResponseFailed = {0xbc8, 0x0, 0x13, 0x2, 0xf0, 0x7, 0x1000000000000000};
#define BackendHandleResponseFailed_value 0xbc8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendHandleEndpointNotFoundExceptionFailed = {0xbc9, 0x0, 0x13, 0x2, 0xf0, 0x7, 0x1000000000000000};
#define BackendHandleEndpointNotFoundExceptionFailed_value 0xbc9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendHandleExceptionFailed = {0xbca, 0x0, 0x13, 0x2, 0xf0, 0x7, 0x1000000000000000};
#define BackendHandleExceptionFailed_value 0xbca
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendEndpointNotFoundExceptionOccured = {0xbcb, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define BackendEndpointNotFoundExceptionOccured_value 0xbcb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendDispatcherClosed = {0xbcc, 0x0, 0x13, 0x3, 0x9, 0x7, 0x1000000000000000};
#define BackendDispatcherClosed_value 0xbcc
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BackendResponseReceivedSessionFault = {0xbcd, 0x0, 0x13, 0x3, 0xf0, 0x7, 0x1000000000000000};
#define BackendResponseReceivedSessionFault_value 0xbcd
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionCreating = {0xfa0, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionCreating_value 0xfa0
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionCreated = {0xfa1, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionCreated_value 0xfa1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR FailedToCreateSession = {0xfa2, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define FailedToCreateSession_value 0xfa2
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionFinished = {0xfa3, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionFinished_value 0xfa3
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionFinishedBecauseOfJobCanceled = {0xfa4, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionFinishedBecauseOfJobCanceled_value 0xfa4
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionFinishedBecauseOfTimeout = {0xfa5, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionFinishedBecauseOfTimeout_value 0xfa5
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionSuspended = {0xfa6, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionSuspended_value 0xfa6
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionSuspendedBecauseOfJobCanceled = {0xfa7, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionSuspendedBecauseOfJobCanceled_value 0xfa7
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionSuspendedBecauseOfTimeout = {0xfa8, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionSuspendedBecauseOfTimeout_value 0xfa8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionRaisedUp = {0xfa9, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionRaisedUp_value 0xfa9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR SessionRaisedUpFailover = {0xfaa, 0x0, 0x13, 0x4, 0x0, 0x2, 0x1000000000000000};
#define SessionRaisedUpFailover_value 0xfaa
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BrokerWorkerUnexpectedlyExit = {0x1388, 0x0, 0x11, 0x2, 0x0, 0x8, 0x4000000000000000};
#define BrokerWorkerUnexpectedlyExit_value 0x1388
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BrokerWorkerMessage = {0x1389, 0x0, 0x11, 0x4, 0x0, 0x8, 0x4000000000000000};
#define BrokerWorkerMessage_value 0x1389
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BrokerWorkerProcessReady = {0x138a, 0x0, 0x11, 0x4, 0x0, 0x8, 0x4000000000000000};
#define BrokerWorkerProcessReady_value 0x138a
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BrokerWorkerProcessExited = {0x138b, 0x0, 0x11, 0x4, 0x0, 0x8, 0x4000000000000000};
#define BrokerWorkerProcessExited_value 0x138b
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BrokerWorkerProcessFailedToInitialize = {0x138c, 0x0, 0x11, 0x3, 0x0, 0x8, 0x4000000000000000};
#define BrokerWorkerProcessFailedToInitialize_value 0x138c
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR UserTraceVerbose = {0x2328, 0x0, 0x13, 0x5, 0x0, 0x9, 0x1000000000000001};
#define UserTraceVerbose_value 0x2328
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR UserTraceInfo = {0x2329, 0x0, 0x13, 0x4, 0x0, 0x9, 0x1000000000000001};
#define UserTraceInfo_value 0x2329
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR UserTraceWarning = {0x232a, 0x0, 0x13, 0x3, 0x0, 0x9, 0x1000000000000001};
#define UserTraceWarning_value 0x232a
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR UserTraceError = {0x232b, 0x0, 0x13, 0x2, 0x0, 0x9, 0x1000000000000001};
#define UserTraceError_value 0x232b
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR UserTraceCritial = {0x232c, 0x0, 0x10, 0x1, 0x0, 0x9, 0x8000000000000001};
#define UserTraceCritial_value 0x232c
//+
// Provider Microsoft-HPC-SOADiag Event Count 11
//+
EXTERN_C __declspec(selectany) const GUID SOADiagTrace = {0xf120775c, 0xdb24, 0x4504, {0xb1, 0xc8, 0x7f, 0x12, 0x0d, 0x80, 0x08, 0xa0}};

//
// Channel
//
#define SOADiagTrace_CHANNEL_AdminChannel 0x10
#define HPC_CHANNEL_Runtime_OP 0x11
#define DebugChannel 0x12

//
// Tasks
//
#define DebugTrace 0x1
#define EventLifecycle 0x2
#define Throttling 0x3
#define DiagMonLifecycle 0x4
//
// Keyword
//
#define TextTracing 0x1

#define StopThrottle_value 0x7d1
#define MSG_TextTracing                      0x10000001L
#define MSG_StringMessage                    0xB000000AL
#define MSG_HostRequestReceived              0xB00003E8L
#define MSG_HostResponseSent                 0xB00003E9L
#define MSG_HostStart                        0xB00003EAL
#define MSG_HostServiceConfigCheck           0xB00003ECL
#define MSG_HostAssemblyLoaded               0xB00003EDL
#define MSG_HostCanceled                     0xB00003EEL
#define MSG_FrontEndRequestReceived          0xB0000BB8L
#define MSG_FrontEndResponseSent             0xB0000BB9L
#define MSG_BackendRequestSent               0xB0000BBAL
#define MSG_BackendResponseReceived          0xB0000BBBL
#define MSG_BackendRequestSentFailed         0xB0000BBCL
#define MSG_BackendResponseReceivedFailed    0xB0000BBDL
#define MSG_FrontEndResponseSentFailed       0xB0000BBEL
#define MSG_FrontEndRequestRejectedClientIdNotMatch 0xB0000BBFL
#define MSG_FrontEndRequestRejectedClientIdInvalid 0xB0000BC0L
#define MSG_FrontEndRequestRejectedClientStateInvalid 0xB0000BC1L
#define MSG_BackendResponseReceivedRetryOperationError 0xB0000BC2L
#define MSG_BackendResponseReceivedRetryLimitExceed 0xB0000BC3L
#define MSG_BackendRequestPutBack            0xB0000BC4L
#define MSG_BackendGeneratedFaultReply       0xB0000BC5L
#define MSG_FrontEndRequestRejectedAuthenticationError 0xB0000BC6L
#define MSG_FrontEndRequestRejectedGeneralError 0xB0000BC7L
#define MSG_BackendHandleResponseFailed      0xB0000BC8L
#define MSG_BackendHandleEndpointNotFoundExceptionFailed 0xB0000BC9L
#define MSG_BackendHandleExceptionFailed     0xB0000BCAL
#define MSG_BackendEndpointNotFoundExceptionOccured 0xB0000BCBL
#define MSG_BackendDispatcherClosed          0xB0000BCCL
#define MSG_BackendResponseReceivedSessionFault 0xB0000BCDL
#define MSG_SessionCreating                  0xB0000FA0L
#define MSG_SessionCreated                   0xB0000FA1L
#define MSG_FailedToCreateSession            0xB0000FA2L
#define MSG_SessionFinished                  0xB0000FA3L
#define MSG_SessionFinishedBecauseOfJobCanceled 0xB0000FA4L
#define MSG_SessionTimeoutToFinished         0xB0000FA5L
#define MSG_SessionSuspended                 0xB0000FA6L
#define MSG_SessionSuspendedBecauseOfJobCanceled 0xB0000FA7L
#define MSG_SessionTimeoutToSuspended        0xB0000FA8L
#define MSG_SessionRaisedUp                  0xB0000FA9L
#define MSG_SessionRaisedUpFailover          0xB0000FAAL
#define MSG_BrokerWorkerUnexpectedlyExitString 0xB0001388L
#define MSG_BrokerWorkerMessageString        0xB0001389L
#define MSG_BrokerWorkerProcessCreated       0xB000138AL
#define MSG_BrokerWorkerProcessExited        0xB000138BL
#define MSG_BrokerWorkerProcessFailedToInitialize 0xB000138CL
#define MSG_UserTraceMessage                 0xB0002328L
#define MSG_PureString                       0xB000271EL
#define MSG_EventReceived                    0xB10003E8L
#define MSG_EventBuffered                    0xB10003E9L
#define MSG_BufferWritten                    0xB10003EAL
#define MSG_BufferDiscarded                  0xB10003EBL
#define MSG_StartThrottle                    0xB10007D0L
#define MSG_StopThrottle                     0xB10007D1L
