package com.microsoft.hpc.soadiagservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-08-01T14:39:07.734+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", name = "ISoaDiagService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.hpc.ObjectFactory.class, ObjectFactory.class, com.microsoft.hpc.session.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface ISoaDiagService {

    @Action(input = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/CleanupTrace", output = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/CleanupTraceResponse", fault = {@FaultAction(className = ISoaDiagServiceCleanupTraceSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "CleanupTrace", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.CleanupTrace")
    @WebMethod(operationName = "CleanupTrace", action = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/CleanupTrace")
    @ResponseWrapper(localName = "CleanupTraceResponse", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.CleanupTraceResponse")
    public void cleanupTrace(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        java.lang.Integer sessionId
    ) throws ISoaDiagServiceCleanupTraceSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryUserTraceByRequest", output = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryUserTraceByRequestResponse", fault = {@FaultAction(className = ISoaDiagServiceQueryUserTraceByRequestSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "QueryUserTraceByRequest", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QueryUserTraceByRequest")
    @WebMethod(operationName = "QueryUserTraceByRequest", action = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryUserTraceByRequest")
    @ResponseWrapper(localName = "QueryUserTraceByRequestResponse", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QueryUserTraceByRequestResponse")
    public void queryUserTraceByRequest(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        java.lang.Integer sessionId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "request", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        javax.xml.ws.Holder<com.microsoft.hpc.RequestData> request
    ) throws ISoaDiagServiceQueryUserTraceByRequestSessionFaultFaultFaultMessage;

    @Action(input = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryForRequest", output = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryForRequestResponse", fault = {@FaultAction(className = ISoaDiagServiceQueryForRequestSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "QueryForRequest", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QueryForRequest")
    @WebMethod(operationName = "QueryForRequest", action = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QueryForRequest")
    @ResponseWrapper(localName = "QueryForRequestResponse", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QueryForRequestResponse")
    public void queryForRequest(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        java.lang.Integer sessionId,
        @WebParam(name = "state", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        com.microsoft.hpc.RequestState state,
        @WebParam(mode = WebParam.Mode.INOUT, name = "token", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        javax.xml.ws.Holder<com.microsoft.hpc.RequestContinuationToken> token,
        @WebParam(mode = WebParam.Mode.OUT, name = "QueryForRequestResult", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        javax.xml.ws.Holder<com.microsoft.hpc.ArrayOfRequestData> queryForRequestResult
    ) throws ISoaDiagServiceQueryForRequestSessionFaultFaultFaultMessage;

    @WebResult(name = "QuerySessionTraceResult", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
    @Action(input = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QuerySessionTrace", output = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QuerySessionTraceResponse", fault = {@FaultAction(className = ISoaDiagServiceQuerySessionTraceSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "QuerySessionTrace", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QuerySessionTrace")
    @WebMethod(operationName = "QuerySessionTrace", action = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/QuerySessionTrace")
    @ResponseWrapper(localName = "QuerySessionTraceResponse", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.QuerySessionTraceResponse")
    public com.microsoft.hpc.ArrayOfTraceEventItem querySessionTrace(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        java.lang.Integer sessionId
    ) throws ISoaDiagServiceQuerySessionTraceSessionFaultFaultFaultMessage;

    @WebResult(name = "DumpTraceResult", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
    @Action(input = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/DumpTrace", output = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/DumpTraceResponse", fault = {@FaultAction(className = ISoaDiagServiceDumpTraceSessionFaultFaultFaultMessage.class, value = "http://hpc.microsoft.com/session/SessionFault")})
    @RequestWrapper(localName = "DumpTrace", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.DumpTrace")
    @WebMethod(operationName = "DumpTrace", action = "http://hpc.microsoft.com/SoaDiagService/ISoaDiagService/DumpTrace")
    @ResponseWrapper(localName = "DumpTraceResponse", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/", className = "com.microsoft.hpc.soadiagservice.DumpTraceResponse")
    public byte[] dumpTrace(
        @WebParam(name = "sessionId", targetNamespace = "http://hpc.microsoft.com/SoaDiagService/")
        java.lang.Integer sessionId
    ) throws ISoaDiagServiceDumpTraceSessionFaultFaultFaultMessage;
}
