
/*
 * 
 */

package com.microsoft.hpc.soadiagservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-08-01T14:39:07.761+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "SoaDiagService", 
                  wsdlLocation = "file:hpc.microsoft.com.SoaDiagService.wsdl",
                  targetNamespace = "http://hpc.microsoft.com/SoaDiagService/") 
public class SoaDiagService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hpc.microsoft.com/SoaDiagService/", "SoaDiagService");
    public final static QName DefaultBindingISoaDiagService = new QName("http://hpc.microsoft.com/SoaDiagService/", "DefaultBinding_ISoaDiagService");
    static {
        URL url = null;
        try {
            url = new URL("file:hpc.microsoft.com.SoaDiagService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoaDiagService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:hpc.microsoft.com.SoaDiagService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoaDiagService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoaDiagService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoaDiagService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoaDiagService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoaDiagService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SoaDiagService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoaDiagService
     */
    @WebEndpoint(name = "DefaultBinding_ISoaDiagService")
    public ISoaDiagService getDefaultBindingISoaDiagService() {
        return super.getPort(DefaultBindingISoaDiagService, ISoaDiagService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoaDiagService
     */
    @WebEndpoint(name = "DefaultBinding_ISoaDiagService")
    public ISoaDiagService getDefaultBindingISoaDiagService(WebServiceFeature... features) {
        return super.getPort(DefaultBindingISoaDiagService, ISoaDiagService.class, features);
    }

}
